### ISSUE TITLE
Command fails with `Cannot read properties of undefined (reading 'command')`

### ISSUE THREAD

**Issue by Flarkk** [pokowaka/vscode-iwyu#6]
Hi,
I've a fresh install of VSCode + clang + iwyu on Ubuntu.
`compile_commands.json` has been generated and provided to the extension.
Launching the command `Include What You Use` fails with the following uncaught error :
`Cannot read properties of undefined (reading 'command')`.

Directly invoking `iwuy_tool` with the same `compile_commands.json` works.

Can anyone help ?
Thanks !

**Comment by findNextStep** [comment]
I fixed by add `python` into /usr/local/bin

`ln /opt/homebrew/bin/python3 ./python`

type python in terminal you may need a command call python

**Comment by Tymon13** [comment]
Doesn't seem to help in my case, still the same error after adding `python` link to PATH
